print('What do you get when you cross a snowman with a vampire?')
input()
print ( "frostbite" )
print()
print(" what do dentist call a astornaut\'s cavity?")
input()
print ("A black hole!")
print ()
print ("knock knock.")
input()
print ("who's there")
input()
print ("interrrupting cow.")
input()
print ("interrupting cow wh ", end='')
print ("-moo!")
       
